### ISSUE TITLE
Kanban board submission

### ISSUE THREAD

**Issue by edi-sipka** [edi-sipka/Vip_Cars_Rails#23]
Our team has 5 members, and we are:

- Edi Šipka ( @edi-sipka )
- Nonhlanhla (@29td )
- Youta Lactio Christabelle ( @Christabelle143)
- Alena Okolike ( @summyalena )
- Praises Tula ( @PraisesPJMT ) 

Our Kanban board is: https://github.com/users/edi-sipka/projects/3

Our Kanban board screenshot is here: 
![image](https://user-images.githubusercontent.com/105216647/212032685-f1c80b74-177c-4f40-b0ac-f455a0b8903a.png)

**Comment by Meltrust** [comment]
Hi @edi-sipka,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a screenshot of the kanban board.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Meltrust** [comment]
Hi @edi-sipka,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- All cards have been pointed✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

- [ ] These are the pointings for the tasks at the moment of this review:

18 @edi-sipka 
12 @summyalena 
18 @Christabelle143 
20 @PraisesPJMT 
15 @29td 

@summyalena has just 12 points, while the others have 15, 18, and 20.  Please, try to balance the points so the rule about "no more than 5 points difference" is met.

Tip:  You can just play around with the points values and/or reassign tasks.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Meltrust** [comment]
Hi @edi-sipka ,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- Pointings have been balanced✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by PraisesPJMT** [comment]
Thanks so much @Meltrust for the amazing feedback and review!
